FROM amazon/aws-for-fluent-bit:latest

# The out_grafana_loki.so loki plugin was generated by cloning the grafana loki project
# https://github.com/grafana/loki
# Command: make fluent-bit-plugin
# Golang must be installed on the computer to compile loki
# The plugin file will be in the folder: clients/cmd/fluent-bit/out_grafana_loki.so
# In the loki root project folder

# Some firelens examples: https://github.com/aws-samples/amazon-ecs-firelens-examples

ADD out_grafana_loki.so /fluent-bit/out_grafana_loki.so

ADD custom-fluent-bit.conf /extra.conf

# The entypont.sh file was copied and modified from aws-fluent-bit project
# https://github.com/aws/aws-for-fluent-bit

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Optional Metrics endpoint
EXPOSE 2020

# Entry point
CMD /entrypoint.sh